name = "StarFox ZHXS Client"
author = "OrzMiku"
version = "1.1.1+mc1.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62e73b742e6e3cb7246cebd88a8ac78a362e43fa91808c21db8e65e258ea4c00"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
