name = "LunarFox ZHXS Client"
author = "OrzMiku"
version = "1.1.1+mc1.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a40f25c02f9848a05f8cf6ac8d6c39113819cdbeae329c5dc37e54558f4e1130"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
